IF OBJECT_ID('tempdb..##RESULTADO_CALIDAD') IS NOT NULL DROP TABLE ##RESULTADO_CALIDAD;

SELECT
    'COD_CLIENTE' AS CAMPO,
    COUNT(*) AS TOTAL_REGISTROS,
    SUM(CASE WHEN COD_CLIENTE IS NULL THEN 1 ELSE 0 END) AS NULOS
INTO ##RESULTADO_CALIDAD
FROM BD_NEGOCIO.dbo.MAESTRO_CLIENTES
WHERE COD_MES = {{COD_MES}};
