-- =========================================================
-- Proceso: Recomendación SSMM (CDV)
-- Descripción:
--   Genera bases de email y SMS para clientes con recomendación
--   de tienda favorita SSMM, segmentando por uso de TC Cencosud.
--
-- Variables disponibles:
--   {{DIA_SEMINI}}   -- lunes de la semana de envío (yyyyMMdd)
--   {{COD_MES}}      -- mes actual de campaña (yyyyMM)
-- =========================================================


/* =========================================================
   1. Clientes que compran en SSMM con otros medios de pago
      (no usan TC Cencosud)
   ========================================================= */

DROP TABLE IF EXISTS #SSMMNOTC
SELECT COD_CLIE,RECOMENDACION_SSMM INTO #SSMMNOTC
FROM BA.MODELO_TIENDA_PREF_ML
WHERE DIA_SEMINI={{DIA_SEMINI}}
AND FLAG_BONU=1
AND FLAG_MOVI=0


/* =========================================================
   2. Clientes que compran en SSMM y sí pagan con TC Cencosud
   ========================================================= */

DROP TABLE IF EXISTS #SSMMSITC
SELECT COD_CLIE,RECOMENDACION_SSMM INTO #SSMMSITC
FROM BA.MODELO_TIENDA_PREF_ML
WHERE DIA_SEMINI={{DIA_SEMINI}}
AND FLAG_BONU=1
AND FLAG_MOVI=1


/* =========================================================
   3. Unir ambos segmentos (SI_TC / NO_TC) contra la tarjeta
      de crédito vigente (LPC) del mes de campaña
   ========================================================= */

DROP TABLE IF EXISTS #PREVIO_RECOM
SELECT 'SI_SSMM_NO_TC' TIPO_BASE,A.COD_CLIE,B.RECOMENDACION_SSMM INTO #PREVIO_RECOM
FROM CRM.DWF_BANC_CENC_TARJ_CRED A
INNER JOIN #SSMMNOTC B ON A.COD_CLIE=B.COD_CLIE
WHERE COD_MES={{COD_MES}}
AND COD_ESTA_TARJ_COMP='LPC'

INSERT INTO #PREVIO_RECOM (TIPO_BASE, COD_CLIE, RECOMENDACION_SSMM)
SELECT 'SI_SSMM_SI_TC' TIPO_BASE,A.COD_CLIE,B.RECOMENDACION_SSMM
FROM CRM.DWF_BANC_CENC_TARJ_CRED A
INNER JOIN #SSMMSITC B ON A.COD_CLIE=B.COD_CLIE
WHERE COD_MES={{COD_MES}}
AND COD_ESTA_TARJ_COMP='LPC'



/* =========================================================
   4. Marcar flag de supresión de email según contacto vigente
      (DNI o CE, según TIPDOC)
   ========================================================= */

ALTER TABLE #PREVIO_RECOM ADD SUPPRESS_EMAIL_FLG VARCHAR (2)

UPDATE A
SET SUPPRESS_EMAIL_FLG=B.SUPPRESS_EMAIL_FLG
FROM #PREVIO_RECOM A
INNER JOIN STG.TEMP_IN_VW_CONTACT_MAE B
ON RIGHT(A.COD_CLIE,8) = B.SOC_SECURITY_NUM WHERE B.TIPDOC=1

UPDATE A
SET SUPPRESS_EMAIL_FLG=B.SUPPRESS_EMAIL_FLG
FROM #PREVIO_RECOM A
INNER JOIN STG.TEMP_IN_VW_CONTACT_MAE B
ON RIGHT(A.COD_CLIE,9) = B.SOC_SECURITY_NUM WHERE B.TIPDOC=2


/* =========================================================
   5. Quedarse solo con clientes habilitados para email ('y')
   ========================================================= */

DROP TABLE IF EXISTS #PREVIO_RECOMfn
SELECT * INTO #PREVIO_RECOMfn FROM #PREVIO_RECOM WHERE SUPPRESS_EMAIL_FLG='y'


/* =========================================================
   6. Declarar y calcular variables de la campaña
      (fechas, ID de campaña, negocio, etc.)
   ========================================================= */

DECLARE @DIA AS VARCHAR(10), @FEC_ENVIO AS VARCHAR(10), @ID_CAMPANA AS VARCHAR(10), @NEGOCIO AS VARCHAR(30),
@INICIO_CAMPANA AS VARCHAR(10), @FIN_CAMPANA AS VARCHAR(10), @NOMBRE_CAMPANA AS VARCHAR(100), @COD_MES AS INT, @ULT_CODIGO_CAMPANA AS VARCHAR(3),
@CANTIDAD_MAXIMA_SMS AS INT, @OBJETIVO_CAMPANA AS VARCHAR(100), @TIPO_CAMPANA_ABIERTA AS TINYINT, @CAMPANA_GRUPO_ESPECIFICA AS TINYINT, @DINAMICA AS VARCHAR(30), @INCENTIVO AS VARCHAR(100)

SET @DIA = CONVERT(VARCHAR(8),GETDATE(),112)
SET @FEC_ENVIO = CONVERT(VARCHAR(8),GETDATE(),112)
SET @NEGOCIO = 'CDV'
SET @NOMBRE_CAMPANA = 'RECOMENDAC_SSMM'+@DIA
SET @INICIO_CAMPANA = @DIA+1
SET @FIN_CAMPANA = CONVERT(VARCHAR(8),DATEADD(D,+16,@DIA),112)
SET @COD_MES = LEFT(@INICIO_CAMPANA,6)
SET @ULT_CODIGO_CAMPANA = (SELECT RIGHT('00'+CAST(ISNULL(RIGHT(MAX(ID_CAMPANA),3)+1,'01') AS VARCHAR(3)),3) FROM CRM.CABECERA_CAMPANAS WHERE COD_MES = @COD_MES)
SET @ID_CAMPANA = 'CM' + RIGHT(@COD_MES,4)+ @ULT_CODIGO_CAMPANA
SET @OBJETIVO_CAMPANA = ''
SET @TIPO_CAMPANA_ABIERTA = 1
SET @CAMPANA_GRUPO_ESPECIFICA = 0
SET @DINAMICA = ''
SET @INCENTIVO = ''

IF OBJECT_ID('TEMPDB..#VARIABLES') IS NOT NULL DROP TABLE #VARIABLES
SELECT TOP 1 @DIA AS DIA, @FEC_ENVIO AS FEC_ENVIO,@ID_CAMPANA AS ID_CAMPANA, @NEGOCIO AS NEGOCIO, @INICIO_CAMPANA AS INICIO_CAMPANA, @FIN_CAMPANA AS FIN_CAMPANA
, @NOMBRE_CAMPANA AS NOMBRE_CAMPANA, @COD_MES AS COD_MES, @CANTIDAD_MAXIMA_SMS AS CANTIDAD_MAXIMA_SMS, @OBJETIVO_CAMPANA AS OBJETIVO_CAMPANA
, @TIPO_CAMPANA_ABIERTA AS TIPO_CAMPANA_ABIERTA, @CAMPANA_GRUPO_ESPECIFICA AS CAMPANA_GRUPO_ESPECIFICA, @DINAMICA AS DINAMICA, @INCENTIVO AS INCENTIVO
INTO #VARIABLES


/* =========================================================
   7. Registrar la campaña en la cabecera de campañas (poner todos los nombres para evitar errores)
   ========================================================= */
INSERT INTO CRM.CABECERA_CAMPANAS (
    COD_MES, ID_CAMPANA, NEGOCIO, NOMBRE_CAMPANA, INICIO_CAMPANA,
    FIN_CAMPANA, OBJETIVO_CAMPANA, TIPO_CAMPANA_ABIERTA,
    CAMPANA_GRUPO_ESPECIFICA, DINAMICA, INCENTIVO, FECHA_ACTUALIZACION
)
SELECT
    COD_MES, ID_CAMPANA, NEGOCIO, NOMBRE_CAMPANA, INICIO_CAMPANA,
    FIN_CAMPANA ,OBJETIVO_CAMPANA, TIPO_CAMPANA_ABIERTA,
    CAMPANA_GRUPO_ESPECIFICA, DINAMICA, INCENTIVO, GETDATE() AS FECHA_ACTUALIZACION
FROM #VARIABLES


/* =========================================================
   8. Armar la base cruda de campaña (TIPO_BASE + COD_CLIE)
   ========================================================= */

IF OBJECT_ID('TEMPDB..#TEMP_BASE_CAMPANA') IS NOT NULL DROP TABLE #TEMP_BASE_CAMPANA
SELECT TIPO_BASE,COD_CLIE
INTO #TEMP_BASE_CAMPANA
FROM #PREVIO_RECOMfn A (NOLOCK), #VARIABLES B


/* =========================================================
   9. Enriquecer con datos de contacto y flags de envío
      (email, celular, flags de emailing/sms/facebook)
   ========================================================= */

IF OBJECT_ID('TEMPDB..#TEMP_BASE_0') IS NOT NULL DROP TABLE #TEMP_BASE_0
SELECT A.TIPO_BASE, A.COD_CLIE, ISNULL(B.EMAIL,'') EMAIL, ISNULL(B.CELULAR,'') CELULAR, ISNULL(B.NOMBRE,'') NOMBRE, ISNULL(B.FLG_EMAILING,0) FLG_EMAILING
, ISNULL(B.FLG_SMS,0) FLG_SMS, ISNULL(B.FLG_FACEBOOK,0) FLG_FACEBOOK, CAST(0 AS TINYINT) AS GRUPO_CONTROL, CAST(0 AS TINYINT) AS BD_SIEMBRA
INTO #TEMP_BASE_0
FROM #TEMP_BASE_CAMPANA A (NOLOCK)
LEFT JOIN CRM.GRAN_BASE_COMUNICACIONES B ON A.COD_CLIE = B.COD_CLIE
AND B.CRM_CAIDAS_GRAN_BASE_EMAIL IN ('8. ENVIO GRAN BASE','1. NO LPC','4. MITIGADO / LINEA <= 300')
AND LEFT(B.CUENTA_TARJETA,6) <>'477151'


/* =========================================================
   10. Reglas de grupo control (sin contacto o en Indecopi)
   ========================================================= */

UPDATE #TEMP_BASE_0 SET FLG_EMAILING=0 WHERE EMAIL=''
UPDATE #TEMP_BASE_0 SET FLG_SMS=0 WHERE CELULAR=''
UPDATE #TEMP_BASE_0 SET GRUPO_CONTROL = 1 WHERE FLG_EMAILING =0 AND FLG_SMS=0
UPDATE #TEMP_BASE_0 SET GRUPO_CONTROL = 1 WHERE RIGHT(COD_CLIE,8) IN (SELECT RIGHT(CODDOC,8) FROM CRM.INDECOPI_ACTUAL )
UPDATE #TEMP_BASE_0 SET GRUPO_CONTROL = 1 WHERE RIGHT(COD_CLIE,8) IN (SELECT RIGHT(CODDOC,8) FROM CRM.INDECOPI )
UPDATE #TEMP_BASE_0 SET FLG_EMAILING =0, FLG_FACEBOOK=0, FLG_SMS=0 WHERE GRUPO_CONTROL = 1


/* =========================================================
   11. Construir la tabla completa para seguimiento
       (datos demográficos, tarjeta, flags finales)
   ========================================================= */

IF OBJECT_ID('TEMPDB..#TEMP_BASE') IS NOT NULL DROP TABLE #TEMP_BASE
SELECT DISTINCT A.TIPO_BASE, A.COD_CLIE, A.NOMBRE, ISNULL(B.ESTADO_TARJETA_COMPRAS,'') AS ESTADO_TARJETA, ISNULL(B.TIENE_BONUS,'') TIENE_BONUS, ISNULL(B.FORMATO_TIENDA_FAVORITA,'') AS FORMATO, '0' AS CONSUMO_MENSUAL
, ISNULL(B.EDAD,'') EDAD, ISNULL(B.DEPARTAMENTO,'')DEPARTAMENTO, ISNULL(B.PROVINCIA,'') PROVINCIA, ISNULL(B.DISTRITO,'') DISTRITO, ISNULL(B.SEXO,'') AS GENERO, ISNULL(B.LINEA_TC_CONSUMO,'0') AS LINEA_CREDITO_CONSUMO
, '' AS PERFIL_RIESGO, A.CELULAR, A.EMAIL, ISNULL(B.FLG_INDECOPI,0) AS FLG_INDECOPI, ISNULL(B.FLG_NO_DESEA,0) AS FLG_NO_DESEA, A.GRUPO_CONTROL AS FLG_GRUPO_CONTROL
, A.FLG_EMAILING AS ENVIO_EMAIL, A.FLG_SMS AS ENVIO_SMS, B.FLG_NO_AUTO_USO_DATOS AS FLG_USO_DATOS, A.FLG_FACEBOOK AS ENVIO_FACEBOOK, 0 AS ENVIO_CALL
INTO #TEMP_BASE
FROM #TEMP_BASE_0 A
LEFT JOIN CRM.GRAN_BASE_COMUNICACIONES B ON A.COD_CLIE = B.COD_CLIE

UPDATE #TEMP_BASE SET GENERO ='' WHERE GENERO ='NO DEFINIDO'


/* =========================================================
   12. Depurar la base contra listas Indecopi (actual e histórica)
   ========================================================= */

DELETE FROM #TEMP_BASE WHERE RIGHT(COD_CLIE,8) IN (SELECT RIGHT(CODDOC,8) FROM CRM.INDECOPI_ACTUAL)
DELETE FROM #TEMP_BASE WHERE RIGHT(COD_CLIE,8) IN (SELECT RIGHT(CODDOC,8) FROM CRM.INDECOPI )
DELETE A FROM #TEMP_BASE A INNER JOIN CRM.INDECOPI_ACTUAL(NOLOCK) B ON RIGHT(A.COD_CLIE,8) = B.CODDOC AND LEFT(A.COD_CLIE,1) = B.TIPDOC
DELETE A FROM #TEMP_BASE A INNER JOIN CRM.INDECOPI_ACTUAL (NOLOCK) B ON RIGHT(A.COD_CLIE,8) = B.VALOR
DELETE A FROM #TEMP_BASE A INNER JOIN CRM.INDECOPI(NOLOCK) B ON RIGHT(A.COD_CLIE,8) = B.CODDOC AND LEFT(A.COD_CLIE,1) = B.TIPDOC
DELETE A FROM #TEMP_BASE A INNER JOIN CRM.INDECOPI (NOLOCK) B ON RIGHT(A.COD_CLIE,8) = B.VALOR


/* =========================================================
   13. Guardar la base definitiva en seguimiento de campañas
   ========================================================= */
INSERT INTO CRM.SEGUIMIENTO_CAMPANAS (
    COD_MES, ID_CAMPANA, TIPO_BASE, COD_CLIE, NOMBRE, ESTADO_TARJETA,
    TIENE_BONUS, FORMATO, CONSUMO_MENSUAL, EDAD, DEPARTAMENTO, PROVINCIA,
    DISTRITO, GENERO, LINEA_CREDITO_CONSUMO, PERFIL_RIESGO, CELULAR, EMAIL,
    FLG_INDECOPI, FLG_NO_DESEA, FLG_GRUPO_CONTROL, ENVIO_EMAIL, ENVIO_SMS,
    FLG_USO_DATOS, ENVIO_FACEBOOK, ENVIO_CALL
)
SELECT
    A.COD_MES, A.ID_CAMPANA, B.TIPO_BASE, B.COD_CLIE, B.NOMBRE, B.ESTADO_TARJETA,
    B.TIENE_BONUS, B.FORMATO, B.CONSUMO_MENSUAL, B.EDAD, B.DEPARTAMENTO, B.PROVINCIA,
    B.DISTRITO, B.GENERO, B.LINEA_CREDITO_CONSUMO, B.PERFIL_RIESGO, B.CELULAR, B.EMAIL,
    B.FLG_INDECOPI, B.FLG_NO_DESEA, B.FLG_GRUPO_CONTROL, B.ENVIO_EMAIL, B.ENVIO_SMS,
    B.FLG_USO_DATOS, B.ENVIO_FACEBOOK, B.ENVIO_CALL
FROM #VARIABLES A, #TEMP_BASE B

/* =========================================================
   14. Base de EMAIL: clientes habilitados con envío email=1
   ========================================================= */

DROP TABLE IF EXISTS ##EMAIL_RECOM_SSMM
SELECT DISTINCT A.EMAIL, A.NOMBRE,A.TIPO_BASE, A.COD_CLIE, B.RECOMENDACION_SSMM
INTO ##EMAIL_RECOM_SSMM
FROM CRM.SEGUIMIENTO_CAMPANAS A(NOLOCK)
INNER JOIN #PREVIO_RECOMfn B ON A.COD_CLIE=B.COD_CLIE
WHERE A.ID_CAMPANA = (SELECT ID_CAMPANA FROM #VARIABLES)
AND A.FLG_GRUPO_CONTROL = 0 AND ENVIO_EMAIL = 1


/* =========================================================
   15. Base de SMS: clientes habilitados con envío SMS=1
   ========================================================= */

DROP TABLE IF EXISTS ##SMS_RECOM_SSMM
SELECT DISTINCT A.CELULAR, A.NOMBRE,A.TIPO_BASE, A.COD_CLIE, B.RECOMENDACION_SSMM
INTO ##SMS_RECOM_SSMM
FROM CRM.SEGUIMIENTO_CAMPANAS A(NOLOCK)
INNER JOIN #PREVIO_RECOMfn B ON A.COD_CLIE=B.COD_CLIE
WHERE A.ID_CAMPANA = (SELECT ID_CAMPANA FROM #VARIABLES)
AND A.FLG_GRUPO_CONTROL = 0 AND ENVIO_SMS = 1


/* =========================================================
   16. Salidas finales (7 tablas de resultado)
   ========================================================= */

-- 16.1 Email · SI_SSMM_SI_TC · WONG
DROP TABLE IF EXISTS ##EMAIL_SI_TC_WONG;
SELECT EMAIL, NOMBRE INTO ##EMAIL_SI_TC_WONG
FROM ##EMAIL_RECOM_SSMM WHERE TIPO_BASE='SI_SSMM_SI_TC' AND RECOMENDACION_SSMM='WONG';

-- 16.2 Email · SI_SSMM_SI_TC · METRO
DROP TABLE IF EXISTS ##EMAIL_SI_TC_METRO;
SELECT EMAIL, NOMBRE INTO ##EMAIL_SI_TC_METRO
FROM ##EMAIL_RECOM_SSMM WHERE TIPO_BASE='SI_SSMM_SI_TC' AND RECOMENDACION_SSMM='METRO';

-- 16.3 Email · SI_SSMM_SI_TC · METRO_ALMACEN
DROP TABLE IF EXISTS ##EMAIL_SI_TC_METRO_ALMACEN;
SELECT EMAIL, NOMBRE INTO ##EMAIL_SI_TC_METRO_ALMACEN
FROM ##EMAIL_RECOM_SSMM WHERE TIPO_BASE='SI_SSMM_SI_TC' AND RECOMENDACION_SSMM='METRO ALMACEN';

-- 16.4 Email · SI_SSMM_NO_TC · WONG
DROP TABLE IF EXISTS ##EMAIL_NO_TC_WONG;
SELECT EMAIL, NOMBRE INTO ##EMAIL_NO_TC_WONG
FROM ##EMAIL_RECOM_SSMM WHERE TIPO_BASE='SI_SSMM_NO_TC' AND RECOMENDACION_SSMM='WONG';

-- 16.5 Email · SI_SSMM_NO_TC · METRO
DROP TABLE IF EXISTS ##EMAIL_NO_TC_METRO;
SELECT EMAIL, NOMBRE INTO ##EMAIL_NO_TC_METRO
FROM ##EMAIL_RECOM_SSMM WHERE TIPO_BASE='SI_SSMM_NO_TC' AND RECOMENDACION_SSMM='METRO';

-- 16.6 Email · SI_SSMM_NO_TC · METRO_ALMACEN
DROP TABLE IF EXISTS ##EMAIL_NO_TC_METRO_ALMACEN;
SELECT EMAIL, NOMBRE INTO ##EMAIL_NO_TC_METRO_ALMACEN
FROM ##EMAIL_RECOM_SSMM WHERE TIPO_BASE='SI_SSMM_NO_TC' AND RECOMENDACION_SSMM='METRO ALMACEN';

-- 16.7 SMS · base completa
DROP TABLE IF EXISTS ##SMS_TODOS;
SELECT CELULAR, NOMBRE, TIPO_BASE, RECOMENDACION_SSMM INTO ##SMS_TODOS
FROM ##SMS_RECOM_SSMM;