IF OBJECT_ID('tempdb..##RESULTADO_RIESGO') IS NOT NULL DROP TABLE ##RESULTADO_RIESGO;

SELECT
    COD_CLIENTE,
    COD_MES,
    SCORE_RIESGO
INTO ##RESULTADO_RIESGO
FROM BD_NEGOCIO.dbo.MODELO_RIESGO
WHERE COD_MES = {{COD_MES}};
